# Generated by Django 3.1.7 on 2022-03-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0008_delete_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='can_be_shown',
            field=models.BooleanField(default=True),
        ),
    ]
