# Generated by Django 3.1.7 on 2022-02-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20220217_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about_me',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='runs',
            field=models.IntegerField(default=1000),
        ),
    ]
