package com.champ.wallstreet;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RegisterAndLoginTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void registerAndLogin() {
    // Test name: registerAndLogin
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://env-again.eba-4f5yrbpe.us-west-1.elasticbeanstalk.com/");
    // 2 | setWindowSize | 1936x1056 | 
    driver.manage().window().setSize(new Dimension(1936, 1056));
    // 3 | click | linkText=Register | 
    driver.findElement(By.linkText("Register")).click();
    // 4 | click | id=id_username | 
    driver.findElement(By.id("id_username")).click();
    // 5 | type | id=id_username | test2
    driver.findElement(By.id("id_username")).sendKeys("test2");
    // 6 | click | id=id_full_name | 
    driver.findElement(By.id("id_full_name")).click();
    // 7 | type | id=id_full_name | Test Two
    driver.findElement(By.id("id_full_name")).sendKeys("Test Two");
    // 8 | click | id=id_email | 
    driver.findElement(By.id("id_email")).click();
    // 9 | type | id=id_email | test2@gmail.com
    driver.findElement(By.id("id_email")).sendKeys("test2@gmail.com");
    // 10 | click | id=id_password1 | 
    driver.findElement(By.id("id_password1")).click();
    // 11 | type | id=id_password1 | test2
    driver.findElement(By.id("id_password1")).sendKeys("test2");
    // 12 | click | id=id_password2 | 
    driver.findElement(By.id("id_password2")).click();
    // 13 | type | id=id_password2 | test2
    driver.findElement(By.id("id_password2")).sendKeys("test2");
    // 14 | click | css=.auth_form__btn-text | 
    driver.findElement(By.cssSelector(".auth_form__btn-text")).click();
    // 15 | click | id=id_username | 
    driver.findElement(By.id("id_username")).click();
    // 16 | type | id=id_username | test2
    driver.findElement(By.id("id_username")).sendKeys("test2");
    // 17 | click | id=id_password | 
    driver.findElement(By.id("id_password")).click();
    // 18 | type | id=id_password | test2
    driver.findElement(By.id("id_password")).sendKeys("test2");
    // 19 | click | css=.auth_form__btn-text | 
    driver.findElement(By.cssSelector(".auth_form__btn-text")).click();
  }
}
